version: '3'

services:
  userservice:
    build: ./userservice
    ports:
      - "8003:8003"
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  priceservice:
    build: ./priceservice
    ports:
      - "8004:8004"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - stockservice

  stockservice:
    build: ./stockservice
    ports:
      - "8001:8001"
    depends_on:
      - moexservice
      - tinkoffservice

  moexservice:
    build: ./moexservice
    ports:
      - "8002:8002"

  tinkoffservice:
    build: ./tinkoffservice
    ports:
      - "8000:8000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

